model.indep.strat<-function(sampleparam,theta,xi,param){
  tauh=sampleparam$tauh
  proph=sampleparam$proph
  tau=sum(proph*tauh)
  return(list(
  sampleparam=sampleparam,
  theta=theta,
  xi=xi,
  param=param,
  rloiy=function(N){rnorm(N,mean=2,sd=1)},
  ploi=function(y){pnorm(y,mean=2,sd=1)},
  ploilim=function(y){pnorm(y,mean=2,sd=1)},
  rloiz=function(y){rnorm(length(y),mean=2,sd=1)},
  dloi=function(y){dnorm(y,mean=2,sd=1)},
  Scheme=StratS(param=sampleparam),
  rho=function(y){1},
  vinf=function(y){tau-tau^2},
  En=function(N){tau*N},
  tau=tau,
  supportY=c(-.5,5)))}
#S
